name: Check if a Docker image can be built

on:
  push:
    branches: [ devel ]
  pull_request:

jobs:

  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      env:
        # @see https://testdriven.io/blog/faster-ci-builds-with-docker-cache/
        # @see https://docs.docker.com/develop/develop-images/build_enhancements/
        COMPOSE_DOCKER_CLI_BUILD: "1"
        DOCKER_BUILDKIT: "1"
      run: |
        docker build . \
           --cache-from macbre/phantomas:latest \
           --build-arg COMMIT_SHA=$(git rev-parse --short HEAD) \
           --tag ${{ github.repository }}

    - name: Inspect built image
      run: |
        docker images
        docker inspect --format='{{json .Config.Labels}}' ${{ github.repository }} | jq

    - name: Run tests inside the Docker container
      run: |
        ./test/server-start.sh

        docker run \
          --network=host \
          --security-opt seccomp=$(pwd)/chrome-seccomp.json \
          ${{ github.repository }} npm t
