# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 15.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # https://github.com/actions/cache/blob/main/examples.md#using-multiple-systems-and-npm-config
    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: npm cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-nodev${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nodev${{ matrix.node-version }}-

    - name: Install dependencies
      run: npm ci

    - name: Run example script
      env:
        DEBUG: "phantomas:browser"
      run: node examples/index.js https://gf.dev/http3-test

    - name: Run tests
      run: |
        ./test/server-start.sh

        npm test

    - name: Check that bin/phantomas.js works
      run: ./bin/phantomas.js http://127.0.0.1:8888/ --pretty | grep "generator" -A4

    - name: Check that bin/phantomas.js handles errors correctly
      run: ./bin/phantomas.js http://127.0.0.1:1234/ 2>&1 | grep "net::ERR_CONNECTION_REFUSED at http://127.0.0.1:1234"
